version: "3"

services:
  web:
    image: local/php:apache-plus
    container_name: web
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    networks:
      - app-network
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www/html/

#Docker Networks
networks:
  app-network:
    driver: bridge
    